version: '2.1'
volumes:
  ipfs:
  plex-config:
services:
  # plex:
  #   # privileged: true
  #   build: ./plex
  #   network_mode: host
  #   volumes:
  #   - 'plex-video:/mnt/video'
  #   - 'plex-config:/var/lib/plexmediaserver/Library/Application Support'
    # ports:
    #   - 32400:32400/tcp
    #   - 3005:3005/tcp
    #   - 8324:8324/tcp
    #   - 32469:32469/tcp
    #   - 1900:1900/udp
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
  ipfs:
    build: ./ipfs
    volumes:
      - 'plex-config:/data/ipfs'
    ports:
      - 4001:4001/tcp
      - 4002:4002/udp
      - 5001:5001/tcp
      - 8080:8080/tcp
      - 8081:8081/tcp
